#!/bin/bash

# Open Claw - Configuration
# Kubernetes test environment automation CLI tool

OPENCLAW_VERSION="1.0.0"
OPENCLAW_NAME="Open Claw"

OPENCLAW_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OPENCLAW_LIB_DIR="${OPENCLAW_ROOT}/lib"
OPENCLAW_MODELS_DIR="${OPENCLAW_ROOT}/models"
OPENCLAW_RECORDS_DIR="${OPENCLAW_ROOT}/records"
OPENCLAW_CONFIG_DIR="${OPENCLAW_ROOT}/config"

OPENCLAW_WEBHOOK_URL="${OPENCLAW_WEBHOOK_URL:-}"
OPENCLAW_WEBHOOK_TIMEOUT="${OPENCLAW_WEBHOOK_TIMEOUT:-10}"
OPENCLAW_WEBHOOK_ENABLED="${OPENCLAW_WEBHOOK_ENABLED:-true}"

OPENCLAW_KUBECTL_BIN="${OPENCLAW_KUBECTL_BIN:-kubectl}"
OPENCLAW_KUBECTL_NAMESPACE="${OPENCLAW_KUBECTL_NAMESPACE:-default}"

OPENCLAW_GRACEFUL_PERIOD="${OPENCLAW_GRACEFUL_PERIOD:-30}"
OPENCLAW_RESTART_BATCH_SIZE="${OPENCLAW_RESTART_BATCH_SIZE:-1}"
OPENCLAW_RESTART_INTERVAL="${OPENCLAW_RESTART_INTERVAL:-5}"

OPENCLAW_HPA_MIN_REPLICAS="${OPENCLAW_HPA_MIN_REPLICAS:-1}"
OPENCLAW_HPA_MAX_REPLICAS="${OPENCLAW_HPA_MAX_REPLICAS:-10}"
OPENCLAW_HPA_CPU_THRESHOLD="${OPENCLAW_HPA_CPU_THRESHOLD:-80}"
OPENCLAW_HPA_MEMORY_THRESHOLD="${OPENCLAW_HPA_MEMORY_THRESHOLD:-80}"

OPENCLAW_RECORD_FORMAT="${OPENCLAW_RECORD_FORMAT:-json}"
OPENCLAW_RECORD_RETENTION_DAYS="${OPENCLAW_RECORD_RETENTION_DAYS:-30}"

OPENCLAW_LOG_LEVEL="${OPENCLAW_LOG_LEVEL:-INFO}"

export OPENCLAW_VERSION OPENCLAW_NAME
export OPENCLAW_ROOT OPENCLAW_LIB_DIR OPENCLAW_MODELS_DIR OPENCLAW_RECORDS_DIR OPENCLAW_CONFIG_DIR
export OPENCLAW_WEBHOOK_URL OPENCLAW_WEBHOOK_TIMEOUT OPENCLAW_WEBHOOK_ENABLED
export OPENCLAW_KUBECTL_BIN OPENCLAW_KUBECTL_NAMESPACE
export OPENCLAW_GRACEFUL_PERIOD OPENCLAW_RESTART_BATCH_SIZE OPENCLAW_RESTART_INTERVAL
export OPENCLAW_HPA_MIN_REPLICAS OPENCLAW_HPA_MAX_REPLICAS OPENCLAW_HPA_CPU_THRESHOLD OPENCLAW_HPA_MEMORY_THRESHOLD
export OPENCLAW_RECORD_FORMAT OPENCLAW_RECORD_RETENTION_DAYS
export OPENCLAW_LOG_LEVEL
